[package]
name = "megalopa"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
color-eyre = "0.6.3"
directories = "5.0.1"
edit = "0.1.5"
slug = "0.1.5"
